### ISSUE TITLE
dnscrypt-proxy-full代码编译错误。经查，makefile中的wget下载代码错误，请大佬核实！

### ISSUE THREAD

**Issue by zxlhhyccc** [project-openwrt/lede#12]
makefile中54行：
![QQ图片20190729131015](https://user-images.githubusercontent.com/45259624/62023169-42afb180-b202-11e9-8cf3-2a7151024b63.png)
二进制执行文件下载地址：
![QQ图片20190729131130](https://user-images.githubusercontent.com/45259624/62023203-68d55180-b202-11e9-89c2-626fc8a60e1c.png)

**Comment by 1715173329** [comment]
@zxlhhyccc 感谢提交问题，将于稍后进行处理。

**Comment by 1715173329** [comment]
fixed at 7f0a18f
