### ISSUE TITLE
Turbo ACC中的AdGuardHome第一次能运行，进不去管理页面，然后按照提示关闭dns加速保存配置，然后再运行不了！

### ISSUE THREAD

**Issue by zxlhhyccc** [project-openwrt/lede#16]
![image](https://user-images.githubusercontent.com/45259624/62377376-3b2b3800-b575-11e9-9e63-e02387a42af7.png)

**Comment by 1715173329** [comment]
@zxlhhyccc 首先，adg的配置是实时保存的，无需关闭后再重启
然后，同样请手动运行adg查看错误信息。

**Comment by 1715173329** [comment]
@zxlhhyccc 关于运行命令你可以在 /etc/init.d/flowoffload 里面查看

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 关于运行命令你可以在 /etc/init.d/flowoffload 里面查看

脚本运行后无提示
![N2$TT_(0X$NX@5E$ @V6~3L](https://user-images.githubusercontent.com/45259624/62379703-11c0db00-b57a-11e9-9e90-91ed189c25e3.png)

**Comment by 1715173329** [comment]
@zxlhhyccc 不是让你运行init，是要运行里面的启动命令。。
例如
AdGuardHome -p 233 -c xxx

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 不是让你运行init，是要运行里面的启动命令。。
> 例如
> AdGuardHome -p 233 -c xxx

第二个问题：
BBR无论如何选择均不能运行
![K@1RF`AD@~U7VVW@ZS4(_RR](https://user-images.githubusercontent.com/45259624/62380500-ed65fe00-b57b-11e9-8a78-cfa49c346546.png)

**Comment by 1715173329** [comment]
@zxlhhyccc 经实测，BBR_MOD需要额外安装组件，故无法启用
你可以选择BBR

**Comment by 1715173329** [comment]
@zxlhhyccc BBR问题已在 2294c0b 中得到处理。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 关于运行命令你可以在 /etc/init.d/flowoffload 里面查看

AdGuardHome的运行命令是什么？

**Comment by 1715173329** [comment]
@zxlhhyccc AdGuardHome -c /etc/AdGuardHome/AdGuardHome.yaml -w /etc/AdGuardHome -h 0.0.0.0 -p 3000

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc BBR问题已在 [2294c0b](https://github.com/project-openwrt/lede/commit/2294c0b0c21c719b16d0489efa6bfd56daa936fe) 中得到处理。

使用luci-app-flowoffload更新后的源码在make menucofing无配置选项

**Comment by 1715173329** [comment]
@zxlhhyccc 。。。蛋疼。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 。。。蛋疼。。

AdGuardHome指令运行情况：
![VR}QC3{MC0@ A{@75U0U$6F](https://user-images.githubusercontent.com/45259624/62383709-f6a69900-b582-11e9-9c54-a273b963385d.png)

**Comment by 1715173329** [comment]
....看起来像是被压缩之后运行出错
你直接运行下 AdGuardHome 看看

**Comment by zxlhhyccc** [comment]
我重新编译未压缩的二进制替换进去的运行结果

**Comment by 1715173329** [comment]
这个是程序问题啊。。不是插件的问题

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 。。。蛋疼。。

无配置项问题缺少一个符号：！
![T~DOE6Y5UW3GN0 O(EJ`MLV](https://user-images.githubusercontent.com/45259624/62383892-864c4780-b583-11e9-9313-9e3c8d81a364.png)

**Comment by 1715173329** [comment]
@zxlhhyccc 并不缺。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 并不缺。。

我加上！后配置出现

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 并不缺。。

加上BBR模块编译报错：
![HT{T(WC09IM6UJP@QN{QGGG](https://user-images.githubusercontent.com/45259624/62384390-e4c5f580-b584-11e9-9735-af589058f2b9.png)

**Comment by 1715173329** [comment]
> > @zxlhhyccc 并不缺。。
> 
> 我加上！后配置出现

我加上!之后并没有出现 另外这样也是不符合规定的
因为BBR_MOD仅适用于4.14内核

**Comment by zxlhhyccc** [comment]
哦

**Comment by zxlhhyccc** [comment]
> > > @zxlhhyccc 并不缺。。
> > 
> > 
> > 我加上！后配置出现
> 
> 我加上!之后并没有出现 另外这样也是不符合规定的
> 因为BBR_MOD仅适用于4.14内核

难道AdGuardHome也是仅适用于4.14？

**Comment by 1715173329** [comment]
@zxlhhyccc AdGuardHome应该是无内核要求的

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc AdGuardHome应该是无内核要求的

我使用的是4.19内核，加上！后配置出现：
![J8ET`T_8LZWSGNRT(6IUV9N](https://user-images.githubusercontent.com/45259624/62384961-4cc90b80-b586-11e9-8918-bdf91060d0b7.png)

**Comment by 1715173329** [comment]
> > @zxlhhyccc AdGuardHome应该是无内核要求的
> 
> 我使用的是4.19内核，加上！后配置出现：
> ![J8ET`T_8LZWSGNRT(6IUV9N](https://user-images.githubusercontent.com/45259624/62384961-4cc90b80-b586-11e9-8918-bdf91060d0b7.png)

现在我这情况很迷。。必须删除bbr_mod&bbr_origin之后flowoffload才会出现。。。

**Comment by zxlhhyccc** [comment]
> > > @zxlhhyccc AdGuardHome应该是无内核要求的
> > 
> > 
> > 我使用的是4.19内核，加上！后配置出现：
> > ![J8ET`T_8LZWSGNRT(6IUV9N](https://user-images.githubusercontent.com/45259624/62384961-4cc90b80-b586-11e9-8918-bdf91060d0b7.png)
> 
> 现在我这情况很迷。。必须删除bbr_mod&bbr_origin之后flowoffload才会出现。。。

你是4.19内核还是4.14内核？我现在改为4.14内核编译试试。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 4.14。。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 4.14。。。

你是编译哪个型号路由的固件。。。AdGuardHome能正常运行么？还有一个就是，打开dns加速后，网页解析出问题，网页打不开。。。

**Comment by 1715173329** [comment]
@zxlhhyccc Newifi_D2
ADG正常运作
ADG开启后需要一点时间启动服务。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc Newifi_D2
> ADG正常运作
> ADG开启后需要一点时间启动服务。。

4.14编译bbr模块也报错。编译不下去。。。

**Comment by zxlhhyccc** [comment]
![79HCJFV5RK)03E_3{$3B3WH](https://user-images.githubusercontent.com/45259624/62385645-3e7bef00-b588-11e9-8117-6f71a4ccc83a.png)

**Comment by 1715173329** [comment]
> > @zxlhhyccc Newifi_D2
> > ADG正常运作
> > ADG开启后需要一点时间启动服务。。
> 
> 4.14编译bbr模块也报错。编译不下去。。。

我打算去掉了。。就用内核提供的原生BBR即可。。在路由器上用魔改版这些实在毫无必要

**Comment by zxlhhyccc** [comment]
> > > @zxlhhyccc Newifi_D2
> > > ADG正常运作
> > > ADG开启后需要一点时间启动服务。。
> > 
> > 
> > 4.14编译bbr模块也报错。编译不下去。。。
> 
> 我打算去掉了。。就用内核提供的原生BBR即可。。在路由器上用魔改版这些实在毫无必要

关键是原生的BBR在ACC上也不运行。。。

**Comment by 1715173329** [comment]
> > > > @zxlhhyccc Newifi_D2
> > > > ADG正常运作
> > > > ADG开启后需要一点时间启动服务。。
> > > 
> > > 
> > > 4.14编译bbr模块也报错。编译不下去。。。
> > 
> > 
> > 我打算去掉了。。就用内核提供的原生BBR即可。。在路由器上用魔改版这些实在毫无必要
> 
> 关键是原生的BBR在ACC上也不运行。。。

![image](https://user-images.githubusercontent.com/22235437/62386146-96672580-b589-11e9-97ee-f5db3a7a1633.png)
4.14内核 测试通过

**Comment by zxlhhyccc** [comment]
> > > > > @zxlhhyccc Newifi_D2
> > > > > ADG正常运作
> > > > > ADG开启后需要一点时间启动服务。。
> > > > 
> > > > 
> > > > 4.14编译bbr模块也报错。编译不下去。。。
> > > 
> > > 
> > > 我打算去掉了。。就用内核提供的原生BBR即可。。在路由器上用魔改版这些实在毫无必要
> > 
> > 
> > 关键是原生的BBR在ACC上也不运行。。。
> 
> ![image](https://user-images.githubusercontent.com/22235437/62386146-96672580-b589-11e9-97ee-f5db3a7a1633.png)
> 4.14内核 测试通过

你用的是大雕的ACC还是你仅仅去掉了bbr魔改模块。。。？

**Comment by 1715173329** [comment]
@zxlhhyccc BBR模块用大雕的了

**Comment by 1715173329** [comment]
@zxlhhyccc 话说，，你那边能看到flowoffload了不。。

**Comment by 1715173329** [comment]
现在你看下，能不能正常编译flowoffload了。。。

**Comment by zxlhhyccc** [comment]
> 现在你看下，能不能正常编译flowoffload了。。。

你重新更新了？

**Comment by zxlhhyccc** [comment]
> 现在你看下，能不能正常编译flowoffload了。。。

luci-app-flowoffload你还是用的大雕的BBR，没加bbr魔改模块。。。。

**Comment by zxlhhyccc** [comment]
> 现在你看下，能不能正常编译flowoffload了。。。

AdGuardHome为何要加到sfe下？4.14、4.19内核不支持。。。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 魔改

**Comment by 1715173329** [comment]
@zxlhhyccc 魔改模块是luci-app-bbr-mod

**Comment by 1715173329** [comment]
@zxlhhyccc sfe是给4.9内核用的，另外谁说的4.14不支持？
再说adg一开始就加到sfe里面了，我只是修修bug

**Comment by 1715173329** [comment]
@zxlhhyccc 还有神tm 4.19不支持。。
adg是集成软件，对内核的要求应该并不苛刻。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc sfe是给4.9内核用的，另外谁说的4.14不支持？
> 再说adg一开始就加到sfe里面了，我只是修修bug

luci-app-sfe的依赖shortcut-fe只能在内核4.9下编译。。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 我当然知道。。。

**Comment by 1715173329** [comment]
这个回复真够乱的

\> 针对ADG问题 
ADG对内核要求并不高，因此无论是在4.9，4.14亦或者4.19都是可用的

\> 针对魔改BBR模块
为避免不必要的麻烦，使用luci-app-bbr-mod进行控制（仅使用4.14内核的设备可看见该选项）

**Comment by 1715173329** [comment]
话说你K3的ADG运行问题处理得怎么样了。。

**Comment by zxlhhyccc** [comment]
> 话说你K3的ADG运行问题处理得怎么样了。。

还没编译完成，目前编译bbr报错：
![98CW{MJG)}BB0VP2S7`@@RS](https://user-images.githubusercontent.com/45259624/62418148-b5eb7480-b695-11e9-9d58-18c019b4afe9.png)

**Comment by zxlhhyccc** [comment]
> 话说你K3的ADG运行问题处理得怎么样了。。

能否加QQ请教？

**Comment by 1715173329** [comment]
@zxlhhyccc 唔。。看图的话，应该是文件冲突了。。
估计的bbr_origin的锅

**Comment by 1715173329** [comment]
@zxlhhyccc 话说为啥要加QQ。。。
TG不好用嘛。。？

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 话说为啥要加QQ。。。
> TG不好用嘛。。？
TG截图不方便。。。。

**Comment by 1715173329** [comment]
@zxlhhyccc ？？？

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc ？？？

这个不知道能不能去掉：
![6B5CC6O42IW3~BJGBC4E0J1](https://user-images.githubusercontent.com/45259624/62418200-dd8f0c80-b696-11e9-933c-c3bc374ab7e7.png)

**Comment by 1715173329** [comment]
@zxlhhyccc 可以。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 可以。。
kmod-bbr应该是由kmod-tcp-bbr提供吧？

**Comment by 1715173329** [comment]
@zxlhhyccc kmod-bbr是bbr_origin。。魔改bbr包里面的
估计也就是原版。。个人觉得没必要。。可以把这玩意儿去掉
而且还造成文件冲突。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc kmod-bbr是bbr_origin。。魔改bbr包里面的
> 估计也就是原版。。个人觉得没必要。。可以把这玩意儿去掉
> 而且还造成文件冲突。。

你的意思是说只用原版（大雕的bbr）就可以了？

**Comment by 1715173329** [comment]
@zxlhhyccc kmod-bbr 与 kmod-tcp-bbr应该是同一个版本。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc kmod-bbr 与 kmod-tcp-bbr应该是同一个版本。。

嗯嗯，估计是，但是bbr-mod这个应该是魔改版吧？

**Comment by 1715173329** [comment]
@zxlhhyccc 是的

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 是的

我现在不编译kmod-bbr只编译bbr-mod，看什么情况。。。

**Comment by zxlhhyccc** [comment]
先解决bbr问题，再来解决adg问题，到时向你请教。。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 好 
说不上请教，大家互相帮助

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 好
> 说不上请教，大家互相帮助

请问ACC你加上了adg吗？

**Comment by 1715173329** [comment]
@zxlhhyccc 一直都在啊

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 一直都在啊

ACC你更新后只是去掉了bbr-mod对么？

**Comment by 1715173329** [comment]
@zxlhhyccc 是的。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 是的。。

你pull了我的部分插件对么？K3的屏幕phicommk3-screenctrl这个你去掉，这个没用，我只是为修改代码做了一个备份，phicomm-k3screenctrl这个包才能完美显示屏幕！

**Comment by 1715173329** [comment]
@zxlhhyccc 好

**Comment by zxlhhyccc** [comment]
k3screenctrl这个是大雕的，也没用，去掉。。。。

**Comment by 1715173329** [comment]
@zxlhhyccc OK

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 好

屏幕代码我花了近一个月才搞定。。。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 辛苦了👍

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 辛苦了👍

去掉kmod-bbr编译成功，等会测试一下。。。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 辛苦了👍

编译guest-wifi这个有uci错误，我一直搞不定，你能否尝试一下？我问作者说能用没关系。。。。确实也是可以使用。。。。
![6)0N8R~1}9RQ}TY}{SE1ZG0](https://user-images.githubusercontent.com/45259624/62418413-dc5fde80-b69a-11e9-8916-c3a027a518ed.png)

**Comment by 1715173329** [comment]
@zxlhhyccc 正常啊。。你的机子上怎么可能有uci命令。。
(不知道为什么在编译的时候会在本机执行init

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc OK

你的源码编译石像鬼qos，你增加了一些依赖，我是直接在op源码增加模块，没使用依赖。。。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 正常啊。。你的机子上怎么可能有uci命令。。
> (不知道为什么在编译的时候会在本机执行init

你编译没执行init？

**Comment by 1715173329** [comment]
@zxlhhyccc 反正op这个设定很奇怪就是了。。init本身没问题

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 反正op这个设定很奇怪就是了。。init本身没问题

你的源码pull更新，出现这个什么情况？
![29~ORQ`TILMVHG3P9AR98X1](https://user-images.githubusercontent.com/45259624/62418529-55f8cc00-b69d-11e9-9e09-518be70bd2c0.png)

**Comment by 1715173329** [comment]
@zxlhhyccc 为了防止修改代码时出现问题，所以增加了dev分支作为测试，等到测试无误后再合并到master主分支

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 为了防止修改代码时出现问题，所以增加了dev分支作为测试，等到测试无误后再合并到master主分支

这个不会搞，请问咋弄？github我还不熟悉。。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 可以参考
https://blog.csdn.net/afeionepiece/article/details/46011389

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 可以参考
> https://blog.csdn.net/afeionepiece/article/details/46011389

我是用SmartGit来pull和push，你直接用git？

**Comment by 1715173329** [comment]
@zxlhhyccc 是的。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 是的。。

ngrokc版本4.18编译不了，缺少相关函数，我提交bug后作者已经修正，请up到新的源码commit。。。。
![R_H8VZZ$UO (%AR$UC@TE](https://user-images.githubusercontent.com/45259624/62418825-657c1300-b6a5-11e9-939d-2ee3ea314836.png)

**Comment by 1715173329** [comment]
luci-app-bbr-mod在内核版本4.14.131中编译通过。
