### ISSUE TITLE
ACC中的bbr-mod代码问题！

### ISSUE THREAD

**Issue by zxlhhyccc** [project-openwrt/lede#17]
![image](https://user-images.githubusercontent.com/45259624/62420271-e47f4480-b6c1-11e9-8b50-70d0d8839df8.png)
这些代码仅仅有bbr-mod和原厂bbr，没有nangqinlang的代码之类。。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 魔改bbr在这种环境下并没有任何实际意义

**Comment by 1715173329** [comment]
@zxlhhyccc 另外flowoffload里面的bbr选项我已经做出了更改。。
参见 7d9146d

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 魔改bbr在这种环境下并没有任何实际意义
你的更改我看到了，我只是想尝试一下魔改能不能启用，不过魔改只能是在4.14下编译，无法在4.19下编译。。。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 另外flowoffload里面的bbr选项我已经做出了更改。。
> 参见 [7d9146d](https://github.com/project-openwrt/lede/commit/7d9146dfde3d86aade72b23095f1db1994335efe)

还有一个问题就是，编译adg后固件增加了10+m，二进制执行文件压缩后其实只有3.7m，不知道为何增加那么多。。。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 另外flowoffload里面的bbr选项我已经做出了更改。。
> 参见 [7d9146d](https://github.com/project-openwrt/lede/commit/7d9146dfde3d86aade72b23095f1db1994335efe)

按照这个说明，bbr-mod应该能在4.19上编译，可是实际不能编译。。。
![ZTI 1Y_~)`3IU$ES5TUE}4](https://user-images.githubusercontent.com/45259624/62420734-f1079b00-b6c9-11e9-8115-94c065cf3fda.png)

**Comment by 1715173329** [comment]
@zxlhhyccc 肯定的啊。。。bbr魔改本来就是针对4.14.*的内核

**Comment by 1715173329** [comment]
@zxlhhyccc adg的话，我这边测试并不会增加10M。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc adg的话，我这边测试并不会增加10M。。

实测bbr-mod很给劲，建议添加bbr-mod加速，只保留bbr和bbr-mod加速即可，其他都去掉。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 我早就去掉了啊。。。你源码没更新吧🌚

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 我早就去掉了啊。。。你源码没更新吧🌚

没更新，但你只保留了bbr，没有bbr-mod。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 我单独出来的啊 luci-app-bbr-mod。。。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 我早就去掉了啊。。。你源码没更新吧🌚

建议重新添加bbr-mod吧，真的给劲。。。。

**Comment by 1715173329** [comment]
@zxlhhyccc

**Comment by zxlhhyccc** [comment]
> luci-app-bbr-mod
luci-app-bbr-mod没用，没勾选启用也是运行中，去掉luci，只在ACC中添加就行。。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 在acc添加的话，4.19内核会编译出错。
另外你在acc里面开了bbr，那肯定会显示在运行啊

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 在acc添加的话，4.19内核会编译出错。
> 另外你在acc里面开了bbr，那肯定会显示在运行啊

不添加在4.19内核也会报错编译不过去，就使用4.14吧，对了，添加后可以不固定非得编译bbr-mod，可以作为选择项。。。

**Comment by 1715173329** [comment]
@zxlhhyccc 懒得搞 单独作为一个app我觉得还行。。

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 在acc添加的话，4.19内核会编译出错。
> 另外你在acc里面开了bbr，那肯定会显示在运行啊

就是说makefile里不作为固定项目编译

**Comment by 1715173329** [comment]
> > @zxlhhyccc 在acc添加的话，4.19内核会编译出错。
> > 另外你在acc里面开了bbr，那肯定会显示在运行啊
> 
> 就是说makefile里不作为固定项目编译

我知道。。但没必要
